parameters:
    wame_generator:
        default_bundle: 'AppBundle'

services:
#    wame_generator.example:
#        class: Wame\GeneratorBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
