parameters:
    wame_generator:
        default_bundle: 'AppBundle'

services:
    Wame\SensioGeneratorBundle\Form\EntityType:
        arguments: ['@service_container']
        tags: [form.type]
    Wame\SensioGeneratorBundle\Form\PropertyType:
        arguments: ['@service_container']
        tags: [form.type]
    Wame\SensioGeneratorBundle\Generator\WameDatatableGenerator:
        public: true
        arguments:
            - '%kernel.root_dir%'
    Wame\SensioGeneratorBundle\Generator\WameEnumGenerator:
        public: true
        arguments:
            - '%kernel.root_dir%'
    Wame\SensioGeneratorBundle\Generator\WameFormGenerator:
        public: true
        arguments:
            - '@doctrine'
            - '%kernel.root_dir%'
    Wame\SensioGeneratorBundle\Generator\WameVoterGenerator:
        public: true
        arguments:
            - '%kernel.root_dir%'
    wame_repository_generator:
        public: true
        class: Wame\SensioGeneratorBundle\Generator\WameRepositoryGenerator
        arguments:
            - '%kernel.root_dir%'
    wame_translation_generator:
        public: true
        class:  Wame\SensioGeneratorBundle\Generator\WameTranslationGenerator
        arguments:
            - '%kernel.root_dir%'
            - '%locale%'
    Wame\SensioGeneratorBundle\Generator\WameEntityGenerator:
        public: true
        arguments:
            - '@wame_translation_generator'
            - '@wame_repository_generator'
            - '%kernel.root_dir%'
