services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $rootDir: '%kernel.root_dir%'
            $locale: '%locale%'

    Wame\GeneratorBundle\:
        resource: '../*'
        exclude: '../{Entity,Migrations,Tests}'

    Wame\GeneratorBundle\Generator\:
        resource: '../Generator/*'
        public: true
